apiVersion: v1
data:
  postgres.conf.yaml: |
    init_config:
    instances:
      - dbm: true
        host: dogfood-backend-postgresql-headless.svc.cluster.local
        port: 5432
        username: datadog
        password: datadog
kind: ConfigMap
metadata:
  name: confd
  namespace: datadog
