apiVersion: v1
data:
  conf.yaml: |
    init_config:
    instances:
      - dbm: true
        host: dogfood-backend-postgresql.svc.cluster.local
        port: 5432
        username: datadog
        password: datadog
kind: ConfigMap
metadata:
  name: postgres
  namespace: datadog
