apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dogfood.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dogfood.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dogfood.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.logs: '[{"source":"go","service":{{ .Chart.Name | quote }}}]'
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dogfood.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dogfood.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gateway-http
              containerPort: {{ .Values.addr }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/healthcheck/livenessProbe
              port: {{ .Values.addr }}
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/healthcheck/readinessProbe
              port: {{ .Values.addr }}
          startupProbe:
            httpGet:
              path: /v1/healthcheck/startupProbe
              port: {{ .Values.addr }}
            failureThreshold: 30
            periodSeconds: 10
          env:
          - name: ADDR
            value: {{ .Values.addr | quote }}
          - name: DOGFOOD_BACKEND_ADDR
            value: {{ .Values.dogfoodBackendAddr }}
          - name: REDIS_HOST
            value: {{ .Values.redisConfig.host }}
          - name: REDIS_ADDR
            value: {{ .Values.redisConfig.addr | quote }}
          - name: REDIS_PASSWORD
            value: {{ .Values.redisConfig.password }}
          - name: RATELIMIT_TIME_UNIT
            value: {{ .Values.ratelimitConfig.timeUnit }}
          - name: RATELIMIT_LIMIT
            value: {{ .Values.ratelimitConfig.limit | quote }}
          - name: DD_SERVICE
            value: dogfood.gateway
          - name: DD_VERSION
            value: {{ .Values.image.tag | default .Chart.AppVersion }}
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- with .Values.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
