apiVersion: v1
kind: Service
metadata:
  name: {{ include "dogfood.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dogfood.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.addr }}
      targetPort: gateway-http
      protocol: TCP
      name: gateway-http
  selector:
    {{- include "dogfood.selectorLabels" . | nindent 4 }}
