// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package healthcheckpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthCheckServiceClient is the client API for HealthCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckServiceClient interface {
	LivenessProbe(ctx context.Context, in *LivenessProbeRequest, opts ...grpc.CallOption) (*LivenessProbeResponse, error)
	ReadinessProbe(ctx context.Context, in *ReadinessProbeRequest, opts ...grpc.CallOption) (*ReadinessProbeResponse, error)
	StartupProbe(ctx context.Context, in *StartupProbeRequest, opts ...grpc.CallOption) (*StartupProbeResponse, error)
}

type healthCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckServiceClient(cc grpc.ClientConnInterface) HealthCheckServiceClient {
	return &healthCheckServiceClient{cc}
}

func (c *healthCheckServiceClient) LivenessProbe(ctx context.Context, in *LivenessProbeRequest, opts ...grpc.CallOption) (*LivenessProbeResponse, error) {
	out := new(LivenessProbeResponse)
	err := c.cc.Invoke(ctx, "/healthcheckpb.v1.HealthCheckService/LivenessProbe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckServiceClient) ReadinessProbe(ctx context.Context, in *ReadinessProbeRequest, opts ...grpc.CallOption) (*ReadinessProbeResponse, error) {
	out := new(ReadinessProbeResponse)
	err := c.cc.Invoke(ctx, "/healthcheckpb.v1.HealthCheckService/ReadinessProbe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckServiceClient) StartupProbe(ctx context.Context, in *StartupProbeRequest, opts ...grpc.CallOption) (*StartupProbeResponse, error) {
	out := new(StartupProbeResponse)
	err := c.cc.Invoke(ctx, "/healthcheckpb.v1.HealthCheckService/StartupProbe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckServiceServer is the server API for HealthCheckService service.
// All implementations should embed UnimplementedHealthCheckServiceServer
// for forward compatibility
type HealthCheckServiceServer interface {
	LivenessProbe(context.Context, *LivenessProbeRequest) (*LivenessProbeResponse, error)
	ReadinessProbe(context.Context, *ReadinessProbeRequest) (*ReadinessProbeResponse, error)
	StartupProbe(context.Context, *StartupProbeRequest) (*StartupProbeResponse, error)
}

// UnimplementedHealthCheckServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHealthCheckServiceServer struct {
}

func (UnimplementedHealthCheckServiceServer) LivenessProbe(context.Context, *LivenessProbeRequest) (*LivenessProbeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LivenessProbe not implemented")
}
func (UnimplementedHealthCheckServiceServer) ReadinessProbe(context.Context, *ReadinessProbeRequest) (*ReadinessProbeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadinessProbe not implemented")
}
func (UnimplementedHealthCheckServiceServer) StartupProbe(context.Context, *StartupProbeRequest) (*StartupProbeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartupProbe not implemented")
}

// UnsafeHealthCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckServiceServer will
// result in compilation errors.
type UnsafeHealthCheckServiceServer interface {
	mustEmbedUnimplementedHealthCheckServiceServer()
}

func RegisterHealthCheckServiceServer(s grpc.ServiceRegistrar, srv HealthCheckServiceServer) {
	s.RegisterService(&HealthCheckService_ServiceDesc, srv)
}

func _HealthCheckService_LivenessProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).LivenessProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheckpb.v1.HealthCheckService/LivenessProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).LivenessProbe(ctx, req.(*LivenessProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthCheckService_ReadinessProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).ReadinessProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheckpb.v1.HealthCheckService/ReadinessProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).ReadinessProbe(ctx, req.(*ReadinessProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthCheckService_StartupProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartupProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).StartupProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheckpb.v1.HealthCheckService/StartupProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).StartupProbe(ctx, req.(*StartupProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheckService_ServiceDesc is the grpc.ServiceDesc for HealthCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "healthcheckpb.v1.HealthCheckService",
	HandlerType: (*HealthCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LivenessProbe",
			Handler:    _HealthCheckService_LivenessProbe_Handler,
		},
		{
			MethodName: "ReadinessProbe",
			Handler:    _HealthCheckService_ReadinessProbe_Handler,
		},
		{
			MethodName: "StartupProbe",
			Handler:    _HealthCheckService_StartupProbe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/healthcheck/healthcheck.proto",
}
